bug1:
	certoraRun BordaBug1.sol:Borda --verify Borda:Borda.spec --msg "Borda bug 1"

bug2:
	certoraRun BordaBug2.sol:Borda --verify Borda:Borda.spec --msg "Borda bug 2"

bug3:
	certoraRun BordaBug3.sol:Borda --verify Borda:Borda.spec --msg "Borda bug 3"

bug4:
	certoraRun BordaBug4.sol:Borda --verify Borda:Borda.spec --msg "Borda bug 4"
